### ISSUE TITLE
UncaughtPromiseError > TypeError Uncaught Promise > Cannot read properties of undefined (reading 'odooEditor') TypeError: Cannot read properties of undefined (reading 'odooEditor')     at ReportEditorWysiwyg.discard (https://abdo21.odoo.com/web/assets/492852c/web_studio.studio_assets.min.js:362:30)     at Object.mainEventHandler (https://abdo21.odoo.com/web/assets/e548ec7/web.assets_web.min.js:1582:77)     at HTMLButtonElement.listener (https://abdo21.odoo.com/web/assets/e548ec7/web.assets_web.min.js:757:15)

### ISSUE THREAD

**Issue by AbdoYesuf** [odoo/documentation#10129]
odoo account description

**Comment by AntoineVDV** [comment]
Hi, I'm closing the issue since it's not related to the documentation repository. To be honest, it's not even clear what it's about, so I suggest creating a support ticket and describing the problem better.
