### ISSUE TITLE
Create a standalone Owl application

### ISSUE THREAD

**Issue by nilgoyette** [odoo/documentation#9052]
I tried following the [Create a standalone Owl application](https://www.odoo.com/documentation/17.0/developer/howtos/standalone_owl_application.html) guide and it fails with the following error:

    web-1   | 2024-04-29 13:30:33,544 1 ERROR odoo_db odoo.http: Exception during request handling. 
    web-1   | Traceback (most recent call last):
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 2189, in __call__
    web-1   |     response = request._serve_db()
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1765, in _serve_db
    web-1   |     return service_model.retrying(self._serve_ir_http, self.env)
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    web-1   |     result = func()
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1792, in _serve_ir_http
    web-1   |     response = self.dispatcher.dispatch(rule.endpoint, args)
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1909, in dispatch
    web-1   |     return self.request.registry['ir.http']._dispatch(endpoint)
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    web-1   |     response = super()._dispatch(endpoint)
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    web-1   |     result = endpoint(**request.params)
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    web-1   |     result = endpoint(self, *args, **params_ok)
    web-1   |   File "/mnt/extra-addons/imeka/controllers/controllers.py", line 9, in standalone_app
    web-1   |     {'session_info': request.env['ir.http'].get_frontend_session_info()}
    web-1   |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 394, in get_frontend_session_info
    web-1   |     'is_website_user': request.env.user.id == request.website.user_id.id,
    web-1   | AttributeError: 'Request' object has no attribute 'website'

I can't find this error by searching on google and there's nothing related to "website" in the guide so I don't know how to fix this error.

Moreover, `&lt;!DOCTYPE html&gt;` should probably be written as `<!DOCTYPE html>`, no?

**Comment by fruedaCode** [comment]
I was able to make it work by adding website=True to the controller:
```python
from odoo.http import request, route, Controller

class YourController(Controller):
    @route("/your_module/standalone_app", auth="public", website=True)
    def standalone_app(self):
        return request.render(
            'your_module.standalone_app',
            {
                'session_info': request.env['ir.http'].get_frontend_session_info(),
            }
        )
```
I hope this helps.

**Comment by nilgoyette** [comment]
Thank you @fruedaCode for trying to help. I won't test because this is not longer useful to the company I work for (we decided to pick an enterprise that actually tries to help their customers), but it might be useful to other people.
